name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Clean theme content
        run: |
          rm -rf website/themes/nostyleplease/content/posts
          # S'assurer que seul le contenu de eveil-de-fork sera généré
          if [ -d "website/themes/nostyleplease/content" ]; then
            touch website/themes/nostyleplease/content/_index.md
            echo '---' > website/themes/nostyleplease/content/_index.md
            echo 'title: ""' >> website/themes/nostyleplease/content/_index.md
            echo '---' >> website/themes/nostyleplease/content/_index.md
          fi

      - name: Build
        working-directory: ./website
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
